---
title: "Escalabilidade"
author: "Jardell"
date: "02/09/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(lmtest)
```


```{r pressure, echo=FALSE}
melhor <- read.delim("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/melhor_total");
melhor <- data.frame(melhor, results = melhor$n * 1000 + melhor$fo);
results <- data.frame(instance= character(), 
                      literatura = double(),
                      one = double(),
                      two = double(),
                      four = double(),
                      eight = double(),
                      ten = double(),
                      twenty = double(),
                      thirty = double(),
                      forty = double(),
                      fifty = double(),
                      sixty = double());

anova <- data.frame(instance= character(),
                      bloco=character(),
                      tratamento=character(),
                      results = double(),
                      tempo = double());

anova_media <- data.frame(instance= character(),
                      bloco=character(),
                      tratamento=character(),
                      media = double(),
                      mediana = double(),
                      minimo = double(),
                      tempo_medio = double(),
                      tempo_mediana = double(),
                      tempo_max = double());

for(instance in melhor$instancia){

#instance <- "RC106";
  
  d_1 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-OneAgent-30-",instance,"-.txt", sep = ""))
  d_2 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-TwoAgent-30-",instance,"-.txt", sep = ""))
  d_4 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-FourAgent-30-",instance,"-.txt", sep = ""))
  d_8 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-EightAgent-30-",instance,"-.txt", sep = ""))
  d_10 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-TenAgent-30-",instance,"-.txt", sep = ""))
  d_50 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-FiftyAgent-30-",instance,"-.txt", sep = ""))
  d_20 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-TwentyAgent-30-",instance,"-.txt", sep = ""))
  d_40 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-FortyAgent-30-",instance,"-.txt", sep = ""))
  d_30 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-ThirtyAgent-30-",instance,"-.txt", sep = ""))
  d_60 <- read.delim(paste("/home/jardell/Documentos/DOUTORADO/Planejamento_de_Experimentos/Trabalho_Final/results_final/Results_BestSolutionNTry-SixtyAgent-30-",instance,"-.txt", sep = ""))

  d_1 <- data.frame(d_1, results = d_1$n * 1000 + d_1$fo)
  d_2 <- data.frame(d_2, results = d_2$n * 1000 + d_2$fo)
  d_4 <- data.frame(d_4, results = d_4$n * 1000 + d_4$fo)
  d_8 <- data.frame(d_8, results = d_8$n * 1000 + d_8$fo)
  d_10 <- data.frame(d_10, results = d_10$n * 1000 + d_10$fo)
  d_20 <- data.frame(d_20, results = d_20$n * 1000 + d_20$fo)
  d_30 <- data.frame(d_30, results = d_30$n * 1000 + d_30$fo)
  d_40 <- data.frame(d_40, results = d_40$n * 1000 + d_40$fo)
  d_50 <- data.frame(d_50, results = d_50$n * 1000 + d_50$fo)
  d_60 <- data.frame(d_60, results = d_60$n * 1000 + d_60$fo)
  
  linha <- data.frame(instance = instance, 
                      literatura = melhor[melhor$instancia == instance, 4],
                      one = mean(d_1$results),
                      two = mean(d_2$results),
                      four = mean(d_4$results),
                      eight = mean(d_8$results),
                      ten = mean(d_10$results),
                      twenty = mean(d_20$results),
                      thirty = mean(d_30$results),
                      forty = mean(d_40$results),
                      fifty = mean(d_50$results),
                      sixty = mean(d_60$results))
  
  results <- rbind(results, linha)
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "01one",
                    media = mean(d_1$results),
                    mediana = median(d_1$results),
                    minimo = min(d_1$results),
                    tempo_medio = mean(d_1$time),
                    tempo_mediana = median(d_1$time),
                    tempo_maximo = max(d_1$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "02two",
                    media = mean(d_2$results),
                    mediana = median(d_2$results),
                    minimo = min(d_2$results),
                    tempo_medio = mean(d_2$time),
                    tempo_mediana = median(d_2$time),
                    tempo_maximo = max(d_2$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "04four",
                    media = mean(d_4$results),
                    mediana = median(d_4$results),
                    minimo = min(d_4$results),
                    tempo_medio = mean(d_4$time),
                    tempo_mediana = median(d_4$time),
                    tempo_maximo = max(d_4$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "08eight",
                    media = mean(d_8$results),
                    mediana = median(d_8$results),
                    minimo = min(d_8$results),
                    tempo_medio = mean(d_8$time),
                    tempo_mediana = median(d_8$time),
                    tempo_maximo = max(d_8$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "10ten",
                    media = mean(d_10$results),
                    mediana = median(d_10$results),
                    minimo = min(d_10$results),
                    tempo_medio = mean(d_10$time),
                    tempo_mediana = median(d_10$time),
                    tempo_maximo = max(d_10$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "20twenty",
                    media = mean(d_20$results),
                    mediana = median(d_20$results),
                    minimo = min(d_20$results),
                    tempo_medio = mean(d_20$time),
                    tempo_mediana = median(d_20$time),
                    tempo_maximo = max(d_20$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "30thirty",
                    media = mean(d_30$results),
                    mediana = median(d_30$results),
                    minimo = min(d_30$results),
                    tempo_medio = mean(d_30$time),
                    tempo_mediana = median(d_30$time),
                    tempo_maximo = max(d_30$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "40forty",
                    media = mean(d_40$results),
                    mediana = median(d_40$results),
                    minimo = min(d_40$results),
                    tempo_medio = mean(d_40$time),
                    tempo_mediana = median(d_40$time),
                    tempo_maximo = max(d_40$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "50fifty",
                    media = mean(d_50$results),
                    mediana = median(d_50$results),
                    minimo = min(d_50$results),
                    tempo_medio = mean(d_50$time),
                    tempo_mediana = median(d_50$time),
                    tempo_maximo = max(d_50$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = instance,
                    bloco= melhor[melhor$instancia == instance, 4],
                    tratamento = "60sixty",
                    media = mean(d_60$results),
                    mediana = median(d_60$results),
                    minimo = min(d_60$results),
                    tempo_medio = mean(d_60$time),
                    tempo_mediana = median(d_60$time),
                    tempo_maximo = max(d_60$time));
  anova_media <- rbind.data.frame(anova_media,aux);
  
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("01one", 30),
                    results = d_1$results,
                    tempo = d_1$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("02two", 30),
                    results = d_2$results,
                    tempo = d_2$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("04four", 30),
                    results = d_4$results,
                    tempo = d_4$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("08eight", 30),
                    results = d_8$results,
                    tempo = d_8$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("10ten", 30),
                    results = d_10$results,
                    tempo = d_10$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("20twenty", 30),
                    results = d_20$results,
                    tempo = d_20$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("30thirty", 30),
                    results = d_30$results,
                    tempo = d_30$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("40forty", 30),
                    results = d_40$results,
                    tempo = d_40$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("50fifty", 30),
                    results = d_50$results,
                    tempo = d_50$time);
  anova <- rbind.data.frame(anova,aux);
  aux <- data.frame(instance = rep(instance, 30),
                    bloco= rep(melhor[melhor$instancia == instance, 4],30),
                    tratamento = rep("60sixty", 30),
                    results = d_60$results,
                    tempo = d_60$time);
  anova <- rbind.data.frame(anova,aux);

}
```

#ANOVA - FO

```{r }
model <- aov(results ~ tratamento, data = anova);
model
summary(model)
pairwise.t.test(anova$results, anova$tratamento, p.adjust.method="bonferroni")
```

```{r }
dwtest(model)

fligner.test (results ~ tratamento, data = anova)

#shapiro.test(resid(model))
qqnorm(resid(model))
qqline(resid(model))

TukeyHSD(model)
```

#ANOVA - TEMPO

```{r }
modelt <- aov(tempo ~ tratamento, data = anova);
modelt
summary(modelt)
pairwise.t.test(anova$tempo, anova$tratamento, p.adjust.method="bonferroni")
```

```{r }

dwtest(modelt)

fligner.test (tempo ~ tratamento, data = anova)

#shapiro.test(resid(model))
qqnorm(resid(modelt))
qqline(resid(modelt))

TukeyHSD(modelt)
```


#ANOVA - RESULTADO MÉDIO

```{r }
model <- aov(media ~ tratamento, data = anova_media);
model
summary(model)
pairwise.t.test(anova_media$media, anova_media$tratamento, p.adjust.method="bonferroni")
```

```{r }
dwtest(model)

fligner.test (media ~ tratamento, data = anova_media)

shapiro.test(resid(model))
qqnorm(resid(model))
qqline(resid(model))

TukeyHSD(model)
```

#ANOVA - TEMPO MÉDIO

```{r }
modelt <- aov(tempo_medio ~ tratamento, data = anova_media);
modelt
summary(modelt)
pairwise.t.test(anova_media$tempo_medio, anova_media$tratamento, p.adjust.method="bonferroni")
```

```{r }

dwtest(modelt)

fligner.test (tempo_medio ~ tratamento, data = anova_media)

shapiro.test(resid(model))
qqnorm(resid(modelt))
qqline(resid(modelt))

TukeyHSD(modelt)
```