#!/bin/bash

#PBS -N PMP
#PBS -l select=1:ncpus=64:features=RAM364:mem=376gb
#PBS -q high_mem
#PBS -m abe
#PBS -M jardell.silva@ufv.br

# Seu roteiro comeca a partir daqui:

# Altera o diretorio corrente para o diretorio de onde foi submetido o script
# Nao remova a linha abaixo
cd $PBS_O_WORKDIR 
 
# Habilita o carregamento de modulos
# Nao remova a linha abaixo
source /etc/profile.d/modules.sh 
 
# Carregar os softwares que serao utilizados no seu script
module load dct-utils/1.0
cpuset
module load java/jre1.8.0_66

# Coloque aqui o comando do software carregado
# Configure de acordo com a sua analise e parametros que desejar

pm="PM_"

#1248---------------------------------------------------------------------------------------------------------------------------------------

for k in I_50_10_S_1-9_1	I_50_10_S_1-49_1	I_50_10_S_1-99_1	I_50_10_S_1-124_1	I_50_15_S_1-9_1	I_50_15_S_1-49_1	I_50_15_S_1-99_1	I_50_15_S_1-124_1	I_50_20_S_1-9_1	I_50_20_S_1-49_1	I_50_20_S_1-99_1	I_50_20_S_1-124_1	I_50_25_S_1-9_1	I_50_25_S_1-49_1	I_50_25_S_1-99_1	I_50_25_S_1-124_1	I_100_10_S_1-9_1	I_100_10_S_1-49_1	I_100_10_S_1-99_1	I_100_10_S_1-124_1	I_100_15_S_1-9_1	I_100_15_S_1-49_1	I_100_15_S_1-99_1	I_100_15_S_1-124_1	I_100_20_S_1-9_1	I_100_20_S_1-49_1	I_100_20_S_1-99_1	I_100_20_S_1-124_1	I_100_25_S_1-9_1	I_100_25_S_1-49_1	I_100_25_S_1-99_1	I_100_25_S_1-124_1
do
#3030---------------------------------------------------------------------------------------------------------------------------------------

	for i in 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28
	do
		cont_cpu=0;

		java -jar PMP_30_0.jar $k ThirtyAgent $i $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_30_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-30));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $(($inicio+19)) $(($inicio+20)) $(($inicio+21)) $(($inicio+22)) $(($inicio+23)) $(($inicio+24)) $(($inicio+25)) $(($inicio+26)) $(($inicio+27)) $(($inicio+28)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_30_1.jar $k ThirtyAgent $(($i+1)) $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_30_1.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-30));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $(($inicio+19)) $(($inicio+20)) $(($inicio+21)) $(($inicio+22)) $(($inicio+23)) $(($inicio+24)) $(($inicio+25)) $(($inicio+26)) $(($inicio+27)) $(($inicio+28)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
				
		wait;

	done
done
