#!/bin/bash

#PBS -N PMP
#PBS -l select=1:ncpus=64:features=RAM364:mem=376gb
#PBS -q high_mem
#PBS -m abe
#PBS -M jardell.silva@ufv.br

# Seu roteiro comeca a partir daqui:

# Altera o diretorio corrente para o diretorio de onde foi submetido o script
# Nao remova a linha abaixo
cd $PBS_O_WORKDIR 
 
# Habilita o carregamento de modulos
# Nao remova a linha abaixo
source /etc/profile.d/modules.sh 
 
# Carregar os softwares que serao utilizados no seu script
module load dct-utils/1.0
cpuset
module load java/jre1.8.0_66

# Coloque aqui o comando do software carregado
# Configure de acordo com a sua analise e parametros que desejar

pm="PM_"

#1248---------------------------------------------------------------------------------------------------------------------------------------

for k in I_50_10_S_1-9_1	I_50_10_S_1-49_1	I_50_10_S_1-99_1	I_50_10_S_1-124_1	I_50_15_S_1-9_1	I_50_15_S_1-49_1	I_50_15_S_1-99_1	I_50_15_S_1-124_1	I_50_20_S_1-9_1	I_50_20_S_1-49_1	I_50_20_S_1-99_1	I_50_20_S_1-124_1	I_50_25_S_1-9_1	I_50_25_S_1-49_1	I_50_25_S_1-99_1	I_50_25_S_1-124_1	I_100_10_S_1-9_1	I_100_10_S_1-49_1	I_100_10_S_1-99_1	I_100_10_S_1-124_1	I_100_15_S_1-9_1	I_100_15_S_1-49_1	I_100_15_S_1-99_1	I_100_15_S_1-124_1	I_100_20_S_1-9_1	I_100_20_S_1-49_1	I_100_20_S_1-99_1	I_100_20_S_1-124_1	I_100_25_S_1-9_1	I_100_25_S_1-49_1	I_100_25_S_1-99_1	I_100_25_S_1-124_1
do	

	for i in 0 4 8 12 16 20 24 28
	do
		cont_cpu=0;
		
		java -jar PMP_1_0.jar $k OneAgent $i $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_1_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		fim=$(($tam_lista-1));		
	
		
		taskset -cp $cont_cpu ${lista[$fim]} ;
		cont_cpu=$((cont_cpu+1));
			
		java -jar PMP_1_1.jar $k OneAgent $(($i+1)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_1_1.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		fim=$(($tam_lista-1));		
	
		taskset -cp $cont_cpu ${lista[$fim]} ;
		cont_cpu=$((cont_cpu+1));
				
		java -jar PMP_1_2.jar $k OneAgent $(($i+2)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_1_2.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		fim=$(($tam_lista-1));		
	
		taskset -cp $cont_cpu ${lista[$fim]} ;
		cont_cpu=$((cont_cpu+1));
				
		java -jar PMP_1_3.jar $k OneAgent $(($i+3)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_1_3.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-1));
		fim=$(($tam_lista-1));		
	
		taskset -cp $cont_cpu ${lista[$fim]} ;
		cont_cpu=$((cont_cpu+1));

#---------------------------------------------------------------------------------------------------------------------------------------

		java -jar PMP_2_0.jar $k TwoAgent $i $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_2_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-2));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_2_1.jar $k TwoAgent $(($i+1)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_2_1.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-2));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_2_2.jar $k TwoAgent $(($i+2)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_2_2.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-2));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_2_3.jar $k TwoAgent $(($i+3)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_2_3.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-2));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
#---------------------------------------------------------------------------------------------------------------------------------------

		java -jar PMP_4_0.jar $k FourAgent $i $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_4_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-4));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_4_1.jar $k FourAgent $(($i+1)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_4_1.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-4));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_4_2.jar $k FourAgent $(($i+2)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_4_2.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-4));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_4_3.jar $k FourAgent $(($i+3)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_4_3.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-4));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
#---------------------------------------------------------------------------------------------------------------------------------------

		java -jar PMP_8_0.jar $k EightAgent $i $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_8_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-8));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_8_1.jar $k EightAgent $(($i+1)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_8_1.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-8));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_8_2.jar $k EightAgent $(($i+2)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_8_2.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-8));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_8_3.jar $k EightAgent $(($i+3)) $pm >> output & 
		sleep 1;
	
		arm=`ps -ef | grep "PMP_8_3.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-8));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
				
		wait;
		
	done

#1050---------------------------------------------------------------------------------------------------------------------------------------

	for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
	do
		cont_cpu=0;

		java -jar PMP_10_0.jar $k TenAgent $i $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_10_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-10));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_50_0.jar $k FiftyAgent $i $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_50_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-50));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $(($inicio+19)) $(($inicio+20)) $(($inicio+21)) $(($inicio+22)) $(($inicio+23)) $(($inicio+24)) $(($inicio+25)) $(($inicio+26)) $(($inicio+27)) $(($inicio+28)) $(($inicio+29)) $(($inicio+30)) $(($inicio+31)) $(($inicio+32)) $(($inicio+33)) $(($inicio+34)) $(($inicio+35)) $(($inicio+36)) $(($inicio+37)) $(($inicio+38)) $(($inicio+39)) $(($inicio+40)) $(($inicio+41)) $(($inicio+42)) $(($inicio+43)) $(($inicio+44)) $(($inicio+45)) $(($inicio+46)) $(($inicio+47)) $(($inicio+48)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
				
		wait;
		
	done

#2040---------------------------------------------------------------------------------------------------------------------------------------

	for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
	do
		cont_cpu=0;

		java -jar PMP_20_0.jar $k TwentyAgent $i $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_20_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-20));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_40_0.jar $k FortyAgent $i $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_40_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-40));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $(($inicio+19)) $(($inicio+20)) $(($inicio+21)) $(($inicio+22)) $(($inicio+23)) $(($inicio+24)) $(($inicio+25)) $(($inicio+26)) $(($inicio+27)) $(($inicio+28)) $(($inicio+29)) $(($inicio+30)) $(($inicio+31)) $(($inicio+32)) $(($inicio+33)) $(($inicio+34)) $(($inicio+35)) $(($inicio+36)) $(($inicio+37)) $(($inicio+38)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
				
		wait;
	
	done

#3030---------------------------------------------------------------------------------------------------------------------------------------

	for i in 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28
	do
		cont_cpu=0;

		java -jar PMP_30_0.jar $k ThirtyAgent $i $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_30_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-30));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $(($inicio+19)) $(($inicio+20)) $(($inicio+21)) $(($inicio+22)) $(($inicio+23)) $(($inicio+24)) $(($inicio+25)) $(($inicio+26)) $(($inicio+27)) $(($inicio+28)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
			
		java -jar PMP_30_0.jar $k ThirtyAgent $(($i+1)) $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_30_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-30));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $(($inicio+19)) $(($inicio+20)) $(($inicio+21)) $(($inicio+22)) $(($inicio+23)) $(($inicio+24)) $(($inicio+25)) $(($inicio+26)) $(($inicio+27)) $(($inicio+28)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
				
		wait;

	done

#60---------------------------------------------------------------------------------------------------------------------------------------

	for i in 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
	do
		cont_cpu=0;
			
		java -jar PMP_60_0.jar $k SixtyAgent $i $pm >> output & 
		sleep 2;
	
		arm=`ps -ef | grep "PMP_60_0.jar" | grep -v "grep" | awk '{print $2}'`;
	
		lista=(`ps -T $arm | grep Rl | grep -v "grep" | awk '{print $2}'`);
	
		tam_lista=${#lista[@]};
		inicio=$(($tam_lista-60));
		fim=$(($tam_lista-1));		
	
		for j in $inicio $(($inicio+1)) $(($inicio+2)) $(($inicio+3)) $(($inicio+4)) $(($inicio+5)) $(($inicio+6)) $(($inicio+7)) $(($inicio+8)) $(($inicio+9)) $(($inicio+10)) $(($inicio+11)) $(($inicio+12)) $(($inicio+13)) $(($inicio+14)) $(($inicio+15)) $(($inicio+16)) $(($inicio+17)) $(($inicio+18)) $(($inicio+19)) $(($inicio+20)) $(($inicio+21)) $(($inicio+22)) $(($inicio+23)) $(($inicio+24)) $(($inicio+25)) $(($inicio+26)) $(($inicio+27)) $(($inicio+28)) $(($inicio+29)) $(($inicio+30)) $(($inicio+31)) $(($inicio+32)) $(($inicio+33)) $(($inicio+34)) $(($inicio+35)) $(($inicio+36)) $(($inicio+37)) $(($inicio+38)) $(($inicio+39)) $(($inicio+40)) $(($inicio+41)) $(($inicio+42)) $(($inicio+43)) $(($inicio+44)) $(($inicio+45)) $(($inicio+46)) $(($inicio+47)) $(($inicio+48)) $(($inicio+49)) $(($inicio+50)) $(($inicio+51)) $(($inicio+52)) $(($inicio+53)) $(($inicio+54)) $(($inicio+55)) $(($inicio+56)) $(($inicio+57)) $(($inicio+58)) $fim
		do
			taskset -cp $cont_cpu ${lista[$j]} ;
			cont_cpu=$((cont_cpu+1));
		done
				
		wait;
		
	done
done
